### ISSUE TITLE
Empty configuration created for contextmod

### ISSUE THREAD

**Issue by thracyturnix** [FoxxMD/reddit-context-bot#151] opened 2024-05-24 22:11 UTC
https://i.imgur.com/ezhYl1Y.png

I have been running the bot 24/7 for some months and recently it is logging that it created an empty config. Since it did this a day ago it has not made any actions as per its config. 

Im not quite sure why it has done this as I havent changed anything on it. Not sure what to do ti fix it. Any advice would be appreciated. 

Thanks

**Comment by FoxxMD** [comment] 2024-05-25 00:44
This was caused by a bug introduced by reddit to the API: https://www.reddit.com/r/redditdev/s/tl1xSIwqH5 and https://www.reddit.com/r/ModSupport/comments/1cz2hcg/comment/l5dlg9a/

Unfortunately it caused this unintended behavior with CM. I have users reporting in the discord server that the problem has now been resolved by reddit but you will still need to go into the **history** (revisions) for the wiki page and revert it to the last good configuration. Then restart the bot. That should get you back to a working state.

**Closed as completed** 2024-05-29 17:35 UTC
